# Generated by Django 5.0.6 on 2024-06-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='account_number',
            new_name='customer_ID',
        ),
    ]
